name: phprog
recipe: symfony
config:
  webroot: ./public
services:
  appserver:
    type: php:8.2
    build_as_root:
      - curl -sS https://get.symfony.com/cli/installer | bash
      - mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
tooling:
  symfony:
    service: appserver